services:
  db:
    image: postgres:16-alpine
    container_name: gym-api-db
    environment:
      POSTGRES_DB: gym-api
      POSTGRES_USER: gym-api_user
      POSTGRES_PASSWORD: gym-api_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym-api_user -d gym-api"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: